const fetch = require('node-fetch');

// Function to generate a detailed description for the card
function createCardDescription(cardText) {
  const { name, type, text, flavorText, color } = cardText;
  let description = `${name}, a Magic the Gathering card of type ${type}.`;

  // Add flavor and effects in a visual context
  description += ` The card features the following abilities: ${text}.`;
  description += ` The flavor text reads: "${flavorText}".`;

  // Include the color for more context in the artwork
  description += ` The card's color identity is ${color}.`;

  // Suggest the style (e.g., fantasy, heroic, dramatic)
  description += ` The art should reflect a ${color} themed, fantasy-style artwork.`;

  return description;
}

async function generateCardImage(cardText) {
  const prompt = createCardDescription(cardText);
  try {
    const response = await fetch('https://api.openai.com/v1/images/generations', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `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`, // Replace with your DALL·E API Key
      },
      body: JSON.stringify({
        prompt: prompt,
        n: 1,
        size: "1024x1024", // You can adjust the size here
      }),
    });

    const data = await response.json();
    if (data.data && data.data[0] && data.data[0].url) {
      return data.data[0].url; // Return the image URL generated by DALL·E
    } else {
      throw new Error("Failed to generate image: No image URL in response");
    }
  } catch (error) {
    console.error("Error generating DALL·E image:", error);
    return "default_image_url.jpg"; // Fallback in case of error
  }
}

module.exports = { createCardDescription, generateCardImage };